"""The per-test time budget in tests/conftest.py, and that it is load-bearing.

A guard nobody has seen fail is a comment, so the cases that matter run real
pytest subprocesses and check the exit code the runner actually uses, not the
wording of a message. The alternative, importing the hook and calling it, would
test the arithmetic in the message rather than the decision made with it.

THE BUDGET IS OVERRIDDEN, not waited out. `TESTINGHQ_SLOW_TEST_BUDGET` drops it
to 0.05s for these runs, so the probe sleeps 0.2s and is still caught, and the
three runs together cost about a second instead of seven.

The first version of this file slept 1.6s against the real 1.0s budget and
needed exemptions of its own: a guard whose proof costs more than the thing it
guards is a guard that gets switched off, and one that is exempt from its own
rule is not quite a guard. `test_this_file_does_not_exempt_itself` holds that
line, so the answer to "this got slow again" is a smaller budget, not a name in
the list.

Only four cases shell out, because each one is a fresh interpreter and a
collection, and a subprocess per assertion is how this file came to cost seven
seconds in the first place. Everything about the budget's own reading is checked
directly, which is what those cases are actually about.

The probe is generated into a temporary directory and the conftest is loaded
explicitly with `-p conftest`, rather than written into the repository's own
`tests/` tree. Writing there works, and is how the first version proved itself,
but a test that leaves a file in the source tree when it is killed is not
something to leave in a suite that has a history of tests leaving things behind.
"""
from __future__ import annotations

import ast
import importlib.util
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "tests"
CONFTEST = TESTS_DIR / "conftest.py"
CONFTEST_SOURCE = CONFTEST.read_text(encoding="utf-8")

#: The budget these runs use. Far below the 1.0s default, so the probe does not
#: have to sleep long to be caught.
TINY_BUDGET = "0.05"

#: Comfortably over TINY_BUDGET, and short enough that the four runs together
#: cost about three seconds. Most of that is the subprocess itself, which is
#: exactly why this file is cheap enough not to need an exemption.
PROBE_SLEEP = 0.1

#: Real hermetic tests to run alongside the probe. Two jobs, not one: the budget
#: only applies once enough tests have run to tell a suite run from a targeted
#: one, and at eighteen a single file plus the probe is nineteen.
COMPANY = ("tests/unit/test_readback_poll.py", "tests/unit/test_messages.py")

PROBE = '''"""Generated by tests/unit/test_suite_time_budget.py. Not a real test."""
import time
{marker}def test_probe_sleeps():
    time.sleep({slow})
'''

#: The marker block is assembled rather than templated inside the module body,
#: because `pytest.mark.None` is a syntax error even in a branch that never
#: runs: Python parses the whole module before anything executes.
MARKED = """import pytest

pytestmark = pytest.mark.allow_network
"""


#: A unique module name for the loaded conftest. NOT `conftest`: pytest
#: registers conftest modules under names that depend on the directory layout and
#: the import mode, so in a full run `sys.modules["conftest"]` can be some other
#: conftest entirely. The first version reused it when present, so these six
#: direct-call tests passed when this file was run alone and failed with an
#: AttributeError in a full suite run: they were asserting against a module that
#: had no `slow_test_budget` in it. Which is the trap
#: `tests/conftest.py` documents for `network_guard` and walked into anyway.
_CONFTEST_MODULE = "testinghq_time_budget_conftest_probe"


def _budget_hook():
    """The `slow_test_budget` function, loaded fresh from the conftest file.

    Executing the conftest a second time is harmless: its module body only
    defines things. The socket patching happens in a fixture, not at import.
    """
    spec = importlib.util.spec_from_file_location(_CONFTEST_MODULE, CONFTEST)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    assert Path(module.__file__).resolve() == CONFTEST.resolve(), (
        f"loaded {module.__file__} instead of {CONFTEST}"
    )
    return module


def _exemptions():
    tree = ast.parse(CONFTEST_SOURCE)
    return ast.literal_eval(
        next(
            node.value
            for node in tree.body
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "SLOW_TEST_EXEMPTIONS"
        )
    )


def _run(*paths: str, slow: float | None = None, marker: str = "",
         budget: str | None = TINY_BUDGET):
    """Run pytest in a subprocess, with the suite conftest loaded explicitly.

    `-p conftest` is how the temporary probe gets the same session hooks a test
    inside `tests/` would have. Without it the probe is outside the conftest's
    directory and the hooks never run, which would make every assertion here
    pass for the wrong reason.
    """
    argv = [sys.executable, "-m", "pytest", "-q", "-p", "conftest", *paths]
    if slow is not None:
        probe = Path(os.environ["PYTEST_TBMPROBE_DIR"]) / "test_zz_probe.py"
        probe.write_text(
            PROBE.format(
                slow=slow,
                marker=MARKED if marker == "allow_network" else "",
            ),
            encoding="utf-8",
        )
        argv.append(str(probe))
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(
        [str(TESTS_DIR), env.get("PYTHONPATH", "")]
    ).strip(os.pathsep)
    if budget is not None:
        env["TESTINGHQ_SLOW_TEST_BUDGET"] = budget
    else:
        env.pop("TESTINGHQ_SLOW_TEST_BUDGET", None)
    return subprocess.run(
        argv, capture_output=True, text=True, cwd=REPO_ROOT, timeout=600, env=env
    )


@pytest.fixture
def probe_dir(tmp_path, monkeypatch):
    monkeypatch.setenv("PYTEST_TBMPROBE_DIR", str(tmp_path))
    return tmp_path


# ---------------------------------------------------------------------------
# Reading the budget. Direct, because that is what these cases are about.
# ---------------------------------------------------------------------------


def test_the_default_budget_is_two_seconds():
    """A guard with no stated default cannot be argued about.

    Two rather than one, and the reason is in the constant's own comment: a
    pytest subprocess costs about 0.8s here before it runs a test and about
    twice that on a CI runner, so a 1s budget puts the guard's own four
    subprocess tests at the threshold. The failure this guards against is a
    multi-second real wait, which 2s still catches with margin to spare."""
    assert "SLOW_TEST_BUDGET = 2.0" in CONFTEST_SOURCE


def test_the_budget_falls_back_to_the_default_when_unset(monkeypatch):
    monkeypatch.delenv("TESTINGHQ_SLOW_TEST_BUDGET", raising=False)
    assert _budget_hook().slow_test_budget() == 2.0


def test_the_budget_is_overridable_from_the_environment(monkeypatch):
    monkeypatch.setenv("TESTINGHQ_SLOW_TEST_BUDGET", "0.05")
    assert _budget_hook().slow_test_budget() == 0.05


def test_a_malformed_budget_refuses_rather_than_falling_back(monkeypatch):
    """A budget that quietly reverts to the default is the exact failure this
    guard exists to prevent, applied to the guard: it would look enforced,
    enforce nothing, and the only way to tell would be to read the variable."""
    monkeypatch.setenv("TESTINGHQ_SLOW_TEST_BUDGET", "soon")
    with pytest.raises(ValueError) as caught:
        _budget_hook().slow_test_budget()
    assert "is not a number" in str(caught.value)


@pytest.mark.parametrize("bad", ["0", "-1"])
def test_a_zero_or_negative_budget_is_refused(monkeypatch, bad):
    """A budget of zero fails every test including an empty one, which is a
    confusing way to learn that zero is not a number of seconds."""
    monkeypatch.setenv("TESTINGHQ_SLOW_TEST_BUDGET", bad)
    with pytest.raises(ValueError) as caught:
        _budget_hook().slow_test_budget()
    assert "greater than zero" in str(caught.value)


def test_an_empty_budget_is_treated_as_unset(monkeypatch):
    """An exported-but-empty variable is a shell script that wrote nothing, not
    a request for a budget of zero."""
    monkeypatch.setenv("TESTINGHQ_SLOW_TEST_BUDGET", "  ")
    assert _budget_hook().slow_test_budget() == 2.0


# ---------------------------------------------------------------------------
# The exemption list is the guard's only hole
# ---------------------------------------------------------------------------


def test_every_exemption_names_a_test_that_shells_out_and_says_why():
    """Both halves are checked: each entry is a real test in a file that genuinely
    shells out, and each carries a reason the guard's own output will print to
    whoever hits it.

    Read with `ast` rather than by slicing the file, because a slice that
    happens to parse is not a check and a comment mentioning the dict breaks one.
    """
    exemptions = _exemptions()
    assert exemptions, "the exemption list is empty, so the guard has no hole at all"
    for node_id, reason in exemptions.items():
        assert "::" in node_id, f"{node_id!r} is not a test node id"
        path = REPO_ROOT / node_id.split("::", 1)[0]
        assert path.is_file(), f"{node_id} names a file that does not exist"
        assert "subprocess" in path.read_text(encoding="utf-8"), (
            f"{node_id} is exempt from the time budget but its file does not "
            "shell out, so there is no reason for it to be slow"
        )
        assert len(reason.strip()) > 40, (
            f"{node_id} has no usable reason, and the guard prints it: {reason!r}"
        )


def test_this_file_does_not_exempt_itself():
    """The whole point of making the budget overridable. Under the default budget
    these tests were slow enough to want exemptions, and a guard exempting its
    own proof is not quite a guard. If that comes back, the answer is a smaller
    budget or fewer subprocesses, not a name in the list."""
    for node_id in _exemptions():
        assert "test_suite_time_budget" not in node_id, (
            f"{node_id} exempts the guard's own test; prove the guard with a "
            f"smaller budget instead"
        )


def test_the_guard_reports_a_stale_exemption():
    """The other half of the hole. An exemption whose test no longer exists is
    a blanket in waiting, and only a whole-suite run can say so, which is why the
    message has to exist in the first place."""
    assert "no test with that id was collected" in CONFTEST_SOURCE
    assert "config.args" in CONFTEST_SOURCE, (
        "staleness can only be decided on a whole-suite run, and that is decided "
        "by whether pytest was given a path"
    )


# ---------------------------------------------------------------------------
# The session decision, in a real subprocess
# ---------------------------------------------------------------------------


def test_a_slow_hermetic_test_fails_the_session(probe_dir):
    """Also the two things that must NOT happen, in the same run because they
    are the same scenario: no false "stale exemption" from a partial
    collection, and a message that says what to do.

    Asserts the override reached the hook by finding the overridden number in
    the failure, which is the one thing a subprocess can show that a direct call
    cannot.
    """
    result = _run(*COMPANY, slow=PROBE_SLEEP)
    combined = result.stdout + result.stderr

    assert result.returncode != 0, (
        "a hermetic test that sleeps past the budget passed. The guard is not "
        f"load-bearing.\n{combined[-2000:]}"
    )
    assert "TOO SLOW" in combined
    # The probe lives outside the rootdir, so pytest collapses its node id to
    # `::test_probe_sleeps` and the filename is not in it. The function name is
    # the part that says which test the guard caught.
    assert "test_probe_sleeps" in combined
    assert f"{TINY_BUDGET}s budget" in combined, (
        "the override did not reach the hook, so this is not a test of the "
        f"override: {combined[-800:]}"
    )

    assert "EXEMPTION IS STALE" not in combined, (
        "a partial collection was reported as stale exemptions, which would make "
        "every targeted run fail and get the guard switched off"
    )
    assert "nject a clock" in combined, "the failure must say what to do instead"
    assert "SLOW_TEST_EXEMPTIONS" in combined, (
        "the failure must name the list a legitimate exception goes in"
    )


def test_a_fast_run_is_indistinguishable_from_no_guard(probe_dir):
    """The other direction, and the one that decides whether the guard survives
    contact with a slow machine. A guard that fires on everything is turned off
    the first time it is wrong."""
    result = _run(*COMPANY)
    assert result.returncode == 0, result.stdout[-3000:] + result.stderr[-2000:]
    assert "TOO SLOW" not in result.stdout


def test_the_marker_is_what_exempts_a_test_from_the_budget(probe_dir):
    """The socket tests are allowed to be slow; that is part of what the marker
    is for. Judging them on wall clock would pressure someone to make a real
    socket test fake, which defeats the reason it exists.

    Driven by marking the probe itself, rather than by running the
    `allow_network` selection, because that selection is thirty-one socket tests
    and ten seconds, and because the direct statement of the rule is the thing
    worth asserting.
    """
    result = _run(*COMPANY, slow=PROBE_SLEEP, marker="allow_network")
    combined = result.stdout + result.stderr
    assert "TOO SLOW" not in combined, combined[-2000:]
    # It really did sleep, so this is not passing because the probe was skipped.
    assert "passed" in combined


def test_a_single_test_run_is_not_judged(probe_dir):
    """`pytest tests/unit/test_one.py` is debugging, not CI, and failing it for
    being slow would teach people to work around the guard."""
    result = _run(slow=PROBE_SLEEP)
    assert result.returncode == 0, (
        "a one-test run of a slow test failed; the budget is for suite runs"
    )
