"""The per-test time budget in tests/conftest.py, and that it is load-bearing.

A guard nobody has seen fail is a comment, so the cases here run real pytest
subprocesses and check the exit code the runner actually uses, not the wording of
a message. The alternative, importing the hook and calling it, would test the
arithmetic in the message rather than the decision made with it.

The three tests that shell out are exempt from the budget themselves, with the
reasons in `SLOW_TEST_EXEMPTIONS` in tests/conftest.py. That is not a special
plea: each of them starts a fresh interpreter and collects a test tree, and
`tests/unit/test_suite_time_budget.py` is verified to contain only tests that
shell out, so the exemption is the rule and not a favour.

The probe is generated into a temporary directory and the conftest is loaded
explicitly with `-p conftest`, rather than written into the repository's own
`tests/` tree. Writing there works, and is how the first version proved itself,
but a test that leaves a file in the source tree when it is killed is not
something to leave in a suite that has a history of tests leaving things behind.
"""
from __future__ import annotations

import ast
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_DIR = REPO_ROOT / "tests"
CONFTEST = TESTS_DIR / "conftest.py"

#: Wide enough to clear the 1.0s budget unambiguously, short enough that the
#: failing cases do not each cost a second.
SLOW = 1.6

#: Real hermetic tests to run alongside the probe. The budget only applies once
#: enough tests have run to tell a suite run from a targeted one, so the probe
#: needs company. These are small and fast, so they do not eat the budget
#: themselves.
COMPANY = ("tests/unit/test_readback.py", "tests/unit/test_readback_poll.py")

PROBE = '''"""Generated by tests/unit/test_suite_time_budget.py. Not a real test."""
import time
{marker}def test_probe_sleeps():
    time.sleep({slow})
'''

#: The marker block is assembled rather than templated inside the module body,
#: because `pytest.mark.None` is a syntax error even in a branch that never
#: runs: Python parses the whole module before anything executes.
MARKED = """import pytest

pytestmark = pytest.mark.allow_network
"""


def _run(*paths: str, slow: float | None = None, marker: str = ""):
    """Run pytest in a subprocess, with the suite conftest loaded explicitly.

    `-p conftest` is how the temporary probe gets the same session hooks a test
    inside `tests/` would have. Without it the probe is outside the conftest's
    directory and the hooks never run, which would make every assertion here
    pass for the wrong reason.
    """
    argv = [sys.executable, "-m", "pytest", "-q", "-p", "conftest", *paths]
    if slow is not None:
        probe = Path(os.environ["PYTEST_TBMPROBE_DIR"]) / "test_zz_probe.py"
        probe.write_text(
            PROBE.format(
                slow=slow,
                marker=MARKED if marker == "allow_network" else "",
            ),
            encoding="utf-8",
        )
        argv.append(str(probe))
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join(
        [str(TESTS_DIR), env.get("PYTHONPATH", "")]
    ).strip(os.pathsep)
    return subprocess.run(
        argv, capture_output=True, text=True, cwd=REPO_ROOT, timeout=600, env=env
    )


@pytest.fixture
def probe_dir(tmp_path, monkeypatch):
    monkeypatch.setenv("PYTEST_TBMPROBE_DIR", str(tmp_path))
    return tmp_path


def _exemptions():
    tree = ast.parse(CONFTEST.read_text(encoding="utf-8"))
    return ast.literal_eval(
        next(
            node.value
            for node in tree.body
            if isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "SLOW_TEST_EXEMPTIONS"
        )
    )


# ---------------------------------------------------------------------------
# The budget exists, and has a number
# ---------------------------------------------------------------------------


def test_the_budget_is_one_second():
    """A guard with no stated budget cannot be argued about, and somebody will
    want to raise it."""
    assert "SLOW_TEST_BUDGET = 1.0" in CONFTEST.read_text(encoding="utf-8")


def test_every_exemption_names_a_test_that_shells_out_and_says_why():
    """The exemption list is the guard's only hole, so both halves are checked:
    that each entry is a real test in a file that genuinely shells out, and
    that each carries a reason the guard's own output will print to whoever hits
    it.

    Read with `ast` rather than by slicing the file, because a slice that
    happens to parse is not a check and a comment mentioning the dict breaks one.
    """
    exemptions = _exemptions()
    assert exemptions, "the exemption list is empty, so the guard has no hole at all"
    for node_id, reason in exemptions.items():
        assert "::" in node_id, f"{node_id!r} is not a test node id"
        path = REPO_ROOT / node_id.split("::", 1)[0]
        assert path.is_file(), f"{node_id} names a file that does not exist"
        assert "subprocess" in path.read_text(encoding="utf-8"), (
            f"{node_id} is exempt from the time budget but its file does not "
            "shell out, so there is no reason for it to be slow"
        )
        assert len(reason.strip()) > 40, (
            f"{node_id} has no usable reason, and the guard prints it: {reason!r}"
        )


def test_the_guard_reports_a_stale_exemption():
    """The other half of the hole. An exemption whose test no longer exists is
    a blanket in waiting, and only a whole-suite run can say so, which is why the
    message has to exist in the first place."""
    source = CONFTEST.read_text(encoding="utf-8")
    assert "no test with that id was collected" in source
    assert "config.args" in source, (
        "staleness can only be decided on a whole-suite run, and that is decided "
        "by whether pytest was given a path"
    )


# ---------------------------------------------------------------------------
# It fails a slow hermetic test
# ---------------------------------------------------------------------------


def test_a_slow_hermetic_test_fails_the_session(probe_dir):
    """Also checks the two things that must NOT happen, in the same run because
    they are the same scenario: no false "stale exemption" from a partial
    collection, and a message that says what to do.
    """
    result = _run(*COMPANY, slow=SLOW)
    combined = result.stdout + result.stderr

    assert result.returncode != 0, (
        "a hermetic test that sleeps past the budget passed. The guard is not "
        f"load-bearing.\n{combined[-2000:]}"
    )
    assert "TOO SLOW" in combined
    # The probe lives outside the rootdir, so pytest collapses its node id to
    # `::test_probe_sleeps` and the filename is not in it. The function name is
    # the part that says which test the guard caught.
    assert "test_probe_sleeps" in combined

    assert "EXEMPTION IS STALE" not in combined, (
        "a partial collection was reported as stale exemptions, which would make "
        "every targeted run fail and get the guard switched off"
    )
    assert "nject a clock" in combined, "the failure must say what to do instead"
    assert "SLOW_TEST_EXEMPTIONS" in combined, (
        "the failure must name the list a legitimate exception goes in"
    )


# ---------------------------------------------------------------------------
# And it does not fire otherwise
# ---------------------------------------------------------------------------


def test_a_fast_run_is_indistinguishable_from_no_guard(probe_dir):
    """The other direction, and the one that decides whether the guard survives
    contact with a slow machine. A guard that fires on everything is turned off
    the first time it is wrong."""
    result = _run(*COMPANY)
    assert result.returncode == 0, result.stdout[-3000:] + result.stderr[-2000:]
    assert "TOO SLOW" not in result.stdout


def test_the_marker_is_what_exempts_a_test_from_the_budget(probe_dir):
    """The socket tests are allowed to be slow; that is part of what the marker
    is for. Judging them on wall clock would pressure someone to make a real
    socket test fake, which defeats the reason it exists.

    Driven by marking the probe itself, rather than by running the
    `allow_network` selection, because that selection is thirty-one socket tests
    and ten seconds, and because the direct statement of the rule is the thing
    worth asserting.
    """
    result = _run(*COMPANY, slow=SLOW, marker="allow_network")
    combined = result.stdout + result.stderr
    assert "TOO SLOW" not in combined, combined[-2000:]
    # It really did sleep, so this is not passing because the probe was skipped.
    assert "1 passed" in combined or "passed" in combined


def test_a_single_test_run_is_not_judged(probe_dir):
    """`pytest tests/unit/test_one.py` is debugging, not CI, and failing it for
    being slow would teach people to work around the guard."""
    result = _run(slow=SLOW)
    assert result.returncode == 0, (
        "a one-test run of a slow test failed; the budget is for suite runs"
    )
